secret:
    databaseUrl: ENC[AES256_GCM,data:3Bz1XqiPnbtBIzWgp86MqG9IahkFzSDVfMA+ktlT4BY5DT8DmXlIkKnPPxzeHsbQK02olsQ=,iv:DUQS9wfvwdNKI88KdiCAiYqh/wvdo4WH20Ec5nDWrOw=,tag:11aAQq1xM6vLeFOppfkVyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoemVUQzAzK0RvM2FlTjl0
            WGIzSXFYblVzN2JZdW1Id2NmM1gyVjQzK1dBCnBNTlJ0MktDZFR6MUpFUWQxMWxO
            Z2VqLzFkU05tWGtST3RvbWJnUk5pMTQKLS0tIC95bnVkKzVBYXZDcDZNMlhocEQ0
            aWlxQTM1SWcxSklmTk1rV1doeHZsbWMKBEbQbGoyp3HBwpu4WB1XfAYTfEY7+uoV
            pkK5m1z0exIHP8QjXkK8l2grQpyUnj9b3lcRYEnJiTeVYaQFrkeJNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ur9dh6j2jssv02xwfdh0ge7al7w5c4xmnyn46f5k8dj5snse2dzsm7nzyy
    lastmodified: "2026-08-14T14:04:26Z"
    mac: ENC[AES256_GCM,data:nWLXUxsNnG04YQx4gt/U3ncrLlj4mXJzc7fil0RX8wZM+X/pnz6avWsc0GfqzE5vUWeXxg14Svp56nFMxplu+hb57bV4cOtP73e43ZeFT3p2DZMfzENAwjN0/9OY3OYu8kojqSsLUNxmDomhokAer15P6FPZa9P/TRxyZuAWVcE=,iv:Zwp0xBrhoiC1dU0+FTnd1q6PLdBCLBgtdfJ2ddE+rpw=,tag:vSlvL3bty16MvXoH4byDlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
